### ISSUE TITLE
Samples?

### ISSUE THREAD

**Issue by raymcdermott** [weavejester/reagi#7]
Are there any usage samples outside of test cases?

**Comment by weavejester** [comment]
Not currently. Reagi's still a little experimental, and some of the places I planned to use it in turned out to be not such a good fit when I put it into practice.

**Comment by raymcdermott** [comment]
That's a shame. I saw a presentation at EuroClojure that got me all fired up about finally getting into FRP style programming ... will you continue it at some time? In the meantime do you think Rx via Java interop is still the best option?

**Comment by weavejester** [comment]
Reagi is experimental, but it's usable and the API has been stable for a while. As far as I'm aware, it's the most complete Clojure FRP library around...

However, when I tried using FRP in practice, I frequently found myself running into coordination issues.  In the end I found more success maintaining a linear log of events that fed into an atom that holds the current state.

**Comment by raymcdermott** [comment]
Ah OK, thanks for that insight.

**Comment by danielsz** [comment]
I would love to study from code samples too. I've seen some uses of reagi in the wild. 
- [Leonardo Borges' Clojure Reactive Programming](https://www.packtpub.com/web-development/clojure-reactive-programming)
- [Using JavaFx from Clojure](http://drowsy.de/blog/?p=7)

Maybe there should be a wiki to keep track of interesting uses.

**Comment by weavejester** [comment]
I've added a wiki in case anyone is interested in doing that.
